apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-agent
  containers:
  - name: shell
    image: bitnami/kubectl:latest
    command:
    - sleep
    args:
    - infinity
    securityContext:
      runAsUser: 0
